# errgro.f — ERRGRO: FVS error/warning message dispatcher (54 codes)
# Translated from: bin/FVSsn_buildDir/errgro.f (664 lines)
#
# LRETRN = true → return after writing message; false → also call fvsSetRtnCode
# IERRN  = error number 1..54
# Severity stored in global ICCODE (1=warning, 2=error, 3=fatal, 4=abort)
# ENTRY GRSTOP         → fvsSetRtnCode(ICCODE); return
# ENTRY fvsGetICCode(I)→ I = ICCODE; return

# Stub for DBSERROR (DBS/SQLite extension — records error to database)
# Implemented fully in extensions/dbs/dbsqlite.jl
DBSERROR(nplt::AbstractString, cmsg::AbstractString) = nothing

function ERRGRO(lretrn::Bool, ierrn::Int32)
    pref = "********   "   # 11 chars

    io  = io_units[JOSTND]
    msg = ""

    if ierrn == Int32(1)
        @printf(io, "\n%sFVS01 ERROR:  INVALID KEYWORD WAS SPECIFIED.  RECORDS READ=%4d\n", pref, IRECNT)
        msg = @sprintf("FVS01 ERROR:  INVALID KEYWORD WAS SPECIFIED.  RECORDS READ=%4d", IRECNT)
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(2)
        @printf(io, "\n%sFVS02 ERROR:  NO \"STOP\" RECORD IN KEYWORD FILE;  RECORDS READ=%4d; END-OF-FILE.\n", pref, IRECNT)
        msg = @sprintf("FVS02 ERROR:  NO \"STOP\" RECORD IN KEYWORD FILE;  RECORDS READ=%4d; END-OF-FILE.", IRECNT)
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(3)
        @printf(io, "\n%sFVS03 WARNING:  FOREST CODE INDICATES THE GEOGRAPHIC LOCATION IS OUTSIDE THE RANGE OF THE MODEL.  DEFAULT CODE IS USED.\n", pref)
        msg = "FVS03 WARNING:  FOREST CODE INDICATES THE GEOGRAPHIC LOCATION IS OUTSIDE THE RANGE OF THE MODEL.  DEFAULT CODE IS USED."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(4)
        @printf(io, "\n%sFVS04 ERROR:  A REQUIRED PARAMETER IS MISSING OR A PARAMETER IS INCORRECT; KEYWORD IGNORED.\n", pref)
        msg = "FVS04 ERROR:  A REQUIRED PARAMETER IS MISSING OR A PARAMETER IS INCORRECT; KEYWORD IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(5)
        @printf(io, "\n%sFVS05 ERROR: EXPRESSION IS TOO LONG.\n", pref)
        msg = "FVS05 ERROR: EXPRESSION IS TOO LONG."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(6)
        @printf(io, "\n%sFVS06 ERROR:  KEYWORD RECORD WAS INCORRECTLY READ. RECORDS READ=%4d\n", pref, IRECNT)
        msg = @sprintf("FVS06 ERROR:  KEYWORD RECORD WAS INCORRECTLY READ. RECORDS READ=%4d", IRECNT)
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(7)
        @printf(io, "\n%sFVS07 WARNING:  A TREEFMT OR SPCODES RECORD FOLLOWS A TREEDATA RECORD.\n", pref)
        msg = "FVS07 WARNING:  A TREEFMT OR SPCODES RECORD FOLLOWS A TREEDATA RECORD."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(8)
        @printf(io, "\n%sFVS08 WARNING:  TOO FEW PROJECTABLE TREE RECORDS.  PROJECTABLE RECORDS:%2d;\n%28sTREE RECORDS:%4d;  STAND ID: %-26s\n", pref, IREC1, "", IRECRD, NPLT)
        msg = @sprintf("FVS08 WARNING:  TOO FEW PROJECTABLE TREE RECORDS.  PROJECTABLE RECORDS:%2d; TREE RECORDS:%4d; STAND ID: %-26s", IREC1, IRECRD, NPLT)
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(9)
        iptknt = LSTKNT - Int32(1)
        @printf(io, "\n%sFVS09 WARNING:  PLOT COUNTS DO NOT MATCH DATA ON THE DESIGN RECORD; DESIGN RECORD DATA USED.\n%29sPLOT COUNT=%4d; NONSTOCKABLE COUNT=%4d\n", pref, "", iptknt, NSTKNT)
        msg = @sprintf("FVS09 WARNING:  PLOT COUNTS DO NOT MATCH DATA ON THE DESIGN RECORD; DESIGN RECORD DATA USED.PLOT COUNT=%4d; NONSTOCKABLE COUNT=%4d", iptknt, NSTKNT)
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(10)
        @printf(io, "\n%sFVS10 ERROR:  OPTION/ACTIVITY STORAGE AREA IS FULL;  REQUEST(S) IGNORED.\n", pref)
        msg = "FVS10 ERROR:  OPTION/ACTIVITY STORAGE AREA IS FULL;  REQUEST(S) IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(11)
        @printf(io, "\n%sFVS11 ERROR:  REQUESTED EXTENSION IS NOT PART OF THIS PROGRAM.\n", pref)
        msg = "FVS11 ERROR:  REQUESTED EXTENSION IS NOT PART OF THIS PROGRAM."
        if ICCODE < Int32(3); global ICCODE = Int32(3); end

    elseif ierrn == Int32(12)
        @printf(io, "\n%sFVS12 ERROR:  ERROR COMPILING EXPRESSION RENDERS IT USELESS.  IT WILL BE IGNORED.\n", pref)
        msg = "FVS12 ERROR:  ERROR COMPILING EXPRESSION RENDERS IT USELESS.  IT WILL BE IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(13)
        @printf(io, "\n%sFVS13 ERROR:  THE MAXIMUM NUMBER OF USEABLE TREE RECORDS HAVE BEEN PROCESSED.  NUMBER READ =%6d; PLOT COUNT =%3d\n", pref, IRECRD, LSTKNT)
        msg = @sprintf("FVS13 ERROR:  THE MAXIMUM NUMBER OF USEABLE TREE RECORDS HAVE BEEN PROCESSED.  NUMBER READ =%6d; PLOT COUNT =%3d", IRECRD, LSTKNT)
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(14)
        @printf(io, "\n%sFVS14 WARNING:  HABITAT/PLANT ASSOCIATION/ECOREGION CODE WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE.\n", pref)
        msg = "FVS14 WARNING:  HABITAT/PLANT ASSOCIATION/ECOREGION CODE WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(15)
        @printf(io, "\n%sFVS15 ERROR:  ATTEMPT TO REDEFINE A RESERVED VARIABLE.  EXPRESSION IGNORED.\n", pref)
        msg = "FVS15 ERROR:  ATTEMPT TO REDEFINE A RESERVED VARIABLE.  EXPRESSION IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(16)
        @printf(io, "\n%sFVS16 ERROR:  KEYWORD ENTERED IS USED IN WRONG CONTEXT AND WAS IGNORED.  RECORDS READ=%4d\n", pref, IRECNT)
        msg = @sprintf("FVS16 ERROR:  KEYWORD ENTERED IS USED IN WRONG CONTEXT AND WAS IGNORED.  RECORDS READ=%4d", IRECNT)
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(17)
        @printf(io, "\n%sFVS17 ERROR:  EVENT MONITOR STORAGE AREA IS FULL.\n", pref)
        msg = "FVS17 ERROR:  EVENT MONITOR STORAGE AREA IS FULL."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(18)
        @printf(io, "\n%sFVS18 ERROR:  ATTEMPT TO SCHEDULE A GROUP OF ACTIVITIES FAILED.\n", pref)
        msg = "FVS18 ERROR:  ATTEMPT TO SCHEDULE A GROUP OF ACTIVITIES FAILED."
        if ICCODE < Int32(3); global ICCODE = Int32(3); end

    elseif ierrn == Int32(19)
        @printf(io, "\n%sFVS19 ERROR:  INCORRECT RECORD TYPE OR END OF DATA FOUND WHILE READING SAMPLE TREE SCRATCH FILE.\n", pref)
        msg = "FVS19 ERROR:  INCORRECT RECORD TYPE OR END OF DATA FOUND WHILE READING SAMPLE TREE SCRATCH FILE."
        if ICCODE < Int32(4); global ICCODE = Int32(4); end

    elseif ierrn == Int32(20)
        @printf(io, "\n%sFVS20 WARNING:  SAMPLE TREE AND STAND ATTRIBUTE TABLE SCRATCH FILE IS EMPTY; TABLE NOT PRINTED.\n", pref)
        msg = "FVS20 WARNING:  SAMPLE TREE AND STAND ATTRIBUTE TABLE SCRATCH FILE IS EMPTY; TABLE NOT PRINTED."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(21)
        @printf(io, "\n%sFVS21 ERROR:  AN EXPRESSION WAS INCORRECTLY COMPUTED; ANSWER IS IGNORED.\n", pref)
        msg = "FVS21 ERROR:  AN EXPRESSION WAS INCORRECTLY COMPUTED; ANSWER IS IGNORED."
        if ICCODE < Int32(1); global ICCODE = Int32(2); end   # note: Fortran source has ICCODE.LT.1 → set 2

    elseif ierrn == Int32(22)
        @printf(io, "\n%sFVS22 ERROR:  OVER 9 ALTERNATIVE ACTIVITY GROUPS SPECIFIED, CURRENT GROUP MAY NOT BE SCHEDULED.\n", pref)
        msg = "FVS22 ERROR:  OVER 9 ALTERNATIVE ACTIVITY GROUPS SPECIFIED, CURRENT GROUP MAY NOT BE SCHEDULED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(23)
        @printf(io, "\n%sFVS23 WARNING:  PLANT ASSOCIATION (FIELD 2) NOT RECOGNIZED.\n", pref)
        msg = "FVS23 WARNING:  PLANT ASSOCIATION (FIELD 2) NOT RECOGNIZED."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(24)
        @printf(io, "\n%sFVS24 WARNING:  MODEL TYPE (FIELD 2) NOT RECOGNIZED.\n", pref)
        msg = "FVS24 WARNING:  MODEL TYPE (FIELD 2) NOT RECOGNIZED."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(25)
        @printf(io, "\n%sFVS25 ERROR:  INCORRECT USE/PLACEMENT OF PARMS; KEYWORD IGNORED.\n", pref)
        msg = "FVS25 ERROR:  INCORRECT USE/PLACEMENT OF PARMS; KEYWORD IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(26)
        @printf(io, "\n%sFVS26 ERROR:  GENERAL REPORTS SCRATCH FILE CAN NOT BE OPENED.\n", pref)
        msg = "FVS26 ERROR:  GENERAL REPORTS SCRATCH FILE CAN NOT BE OPENED."
        if ICCODE < Int32(3); global ICCODE = Int32(3); end

    elseif ierrn == Int32(27)
        @printf(io, "\n%sFVS27 WARNING:  CALCULATED CALIBRATION VALUE OUTSIDE REASONABLE RANGE. CALIBRATION OF THIS SPECIES BEING TURNED OFF.\n", pref)
        msg = "FVS27 WARNING:  CALCULATED CALIBRATION VALUE OUTSIDE REASONABLE RANGE. CALIBRATION OF THIS SPECIES BEING TURNED OFF."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(28)
        @printf(io, "\n%sFVS28 ERROR:  MAXIMUM NUMBER OF 30 SPECIES GROUPS HAS ALREADY BEEN DEFINED; KEYWORD IGNORED.\n", pref)
        msg = "FVS28 ERROR:  MAXIMUM NUMBER OF 30 SPECIES GROUPS HAS ALREADY BEEN DEFINED; KEYWORD IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(29)
        @printf(io, "\n%sFVS29 ERROR:  A SPECIES CODE WAS NOT RECOGNIZED. THIS SPECIES WILL BE IGNORED.\n", pref)
        msg = "FVS29 ERROR:  A SPECIES CODE WAS NOT RECOGNIZED. THIS SPECIES WILL BE IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(30)
        @printf(io, "\n%sFVS30 ERROR:  KEYWORD WAS USED OUT OF REQUIRED SEQUENCE AND IS IGNORED.\n", pref)
        msg = "FVS30 ERROR:  KEYWORD WAS USED OUT OF REQUIRED SEQUENCE AND IS IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(31)
        @printf(io, "\n%sFVS31 ERROR:  .KCP OR .ADD FILE CAN NOT BE OPENED.\n", pref)
        msg = "FVS31 ERROR:  .KCP OR .ADD FILE CAN NOT BE OPENED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(32)
        @printf(io, "\n%sFVS32 WARNING:  PV REFERENCE CODE WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE.\n", pref)
        msg = "FVS32 WARNING:  PV REFERENCE CODE WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(33)
        @printf(io, "\n%sFVS33 WARNING:  PV CODE WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE.\n", pref)
        msg = "FVS33 WARNING:  PV CODE WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(34)
        @printf(io, "\n%sFVS34 WARNING:  PV CODE/PV REFERENCE CODE COMBINATION WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE.\n", pref)
        msg = "FVS34 WARNING:  PV CODE/PV REFERENCE CODE COMBINATION WAS NOT RECOGNIZED; HABITAT/PLANT ASSOCIATION/ECOREGION SET TO DEFAULT CODE."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(35)
        @printf(io, "\n%sFVS35 WARNING:  THE NUMBER OF NONSTOCKABLE PLOTS EQUALS THE TOTAL NUMBER OF PLOTS.\n%29sNUMBER OF NONSTOCKABLE PLOTS SET TO ZERO.\n", pref, "")
        msg = "FVS35 WARNING:  THE NUMBER OF NONSTOCKABLE PLOTS EQUALS THE TOTAL NUMBER OF PLOTS. NUMBER OF NONSTOCKABLE PLOTS SET TO ZERO."
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(36)
        @printf(io, "\n%sFVS36 WARNING:  EXCESSIVE TREE HEIGHT: UNABLE TO CALCULATE VOLUME FOR TREE RECORD, VOLUME SET TO ZERO\n", pref)
        msg = "FVS36 WARNING:  EXCESSIVE TREE HEIGHT: UNABLE TO CALCULATE VOLUME FOR TREE RECORD, VOLUME SET TO ZERO"
        if ICCODE < Int32(1); global ICCODE = Int32(1); end

    elseif ierrn == Int32(37)
        @printf(io, "\n%sFVS37 ERROR:  MAXIMUM NUMBER OF 30 POINT GROUPS HAS ALREADY BEEN DEFINED; KEYWORD IGNORED.\n", pref)
        msg = "FVS37 ERROR:  MAXIMUM NUMBER OF 30 POINT GROUPS HAS ALREADY BEEN DEFINED; KEYWORD IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(2); end

    elseif ierrn == Int32(38)
        @printf(io, "\n%sFVS38 ERROR:  MORE PLOTS FOUND IN TREE DATA THAN SPECIFIED IN STAND DATA; PROJECTION TERMINATED.\n", pref)
        msg = "FVS38 ERROR:  MORE PLOTS FOUND IN TREE DATA THAN SPECIFIED IN STAND DATA; PROJECTION TERMINATED."
        if ICCODE < Int32(3); global ICCODE = Int32(3); end

    elseif ierrn == Int32(39)
        @printf(io, "\n%sFVS39 ERROR:  USER DEFINED COMPUTE VARIABLE NAME CONTAINS INVALID SPECIAL CHARACTERS. PROJECTION TERMINATED.\n", pref)
        msg = "FVS39 ERROR:  USER DEFINED COMPUTE VARIABLE NAME CONTAINS INVALID SPECIAL CHARACTERS. PROJECTION TERMINATED."
        if ICCODE < Int32(3); global ICCODE = Int32(3); end

    elseif ierrn == Int32(40)
        @printf(io, "\n%sFVS40 WARNING:  TREE RECORD REPRESENTING GREATER THAN 1000 TPA ENCOUNTERED. MAY CAUSE MATHEMATICAL ERRORS.\n", pref)
        msg = "FVS40 WARNING:  TREE RECORD REPRESENTING GREATER THAN 1000 TPA ENCOUNTERED. MAY CAUSE MATHEMATICAL ERRORS."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end   # note: Fortran says ICCODE.LT.2 → ICCODE=1

    elseif ierrn == Int32(41)
        @printf(io, "\n%sFVS41 WARNING:  INITIAL STAND STOCKING IS MORE THAN 5%% ABOVE LIMIT, SDI MAXIMUM RESET.\n", pref)
        msg = "FVS41 WARNING:  INITIAL STAND STOCKING IS MORE THAN 5% ABOVE LIMIT, SDI MAXIMUM RESET."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(42)
        @printf(io, "\n%sFVS42 WARNING: IMPROPER FIELD INPUT IDENTIFIED. DEFAULT VALUE FOR FIELD WILL BE USED\n", pref)
        msg = "FVS42 WARNING: IMPROPER FIELD INPUT IDENTIFIED. DEFAULT VALUE FOR FIELD WILL BE USED"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(43)
        @printf(io, "\n%sFVS43 WARNING: FIAVBC REQUESTED BUT ECODIVISION CODE NOT RECOGNIZED OR MISSING. USING \"0000\" BY DEFAULT\n", pref)
        msg = "FVS43 WARNING: FIAVBC REQUESTED BUT ECODIVISION CODE NOT RECOGNIZED OR MISSING. USING \"0000\" BY DEFAULT"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(44)
        @printf(io, "\n%sFVS44 WARNING: STATE CODE MISSING FROM INPUT.  DEFAULT WOODLAND VOLUME EQUATIONS WILL BE USED FOR FIAVBC.\n", pref)
        msg = "FVS44 WARNING: STATE CODE MISSING FROM INPUT.  DEFAULT WOODLAND VOLUME EQUATIONS WILL BE USED  FOR FIAVBC."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(45)
        @printf(io, "\n%sFVS45 WARNING: BFVOLEQU KEYWORD NO LONGER ACTIVE\n", pref)
        msg = "FVS45 WARNING: BFVOLEQU KEYWORD NO LONGER ACTIVE"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(46)
        @printf(io, "\n%sFVS46 WARNING: CFVOLEQU KEYWORD NO LONGER ACTIVE\n", pref)
        msg = "FVS46 WARNING: CFVOLEQU KEYWORD NO LONGER ACTIVE"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(47)
        @printf(io, "\n%sFVS47 WARNING: A DEPRECATED BOARD-FOOT VOLUME COMPUTATION METHOD HAS BEEN REQUESTED.  \n%12sMETHOD CODE 6 (NATIONAL VOLUME ESTIMATOR LIBRARY) WILL BE USED BY DEFAULT.\n", pref, "")
        msg = "FVS47 WARNING: A DEPRECATED BOARD-FOOT VOLUME COMPUTATION METHOD HAS BEEN REQUESTED.  METHOD CODE 6 (NATIONAL VOLUME ESTIMATOR LIBRARY) WILL BE USED BY DEFAULT."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(48)
        @printf(io, "\n%sFVS48 WARNING: A DEPRECATED CUBIC FOOT VOLUME COMPUTATION METHOD HAS BEEN REQUESTED.  \n%12sMETHOD CODE 6 (NATIONAL VOLUME ESTIMATOR LIBRARY) WILL BE USED BY DEFAULT.\n", pref, "")
        msg = "FVS48 WARNING: A DEPRECATED CUBIC FOOT VOLUME COMPUTATION METHOD HAS BEEN REQUESTED.  METHOD CODE 6 (NATIONAL VOLUME ESTIMATOR LIBRARY) WILL BE USED BY DEFAULT."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(49)
        @printf(io, "\n%sFVS49 WARNING: VOLUME KEYWORD HAS BEEN RECOGNIZED \n%12sBUT HAS BEEN DEACTIVATED BY A PREVIOUS CALL TO USE FIAVBC \n%12sFOR COMPUTATION OF CUBIC FOOT VOLUMES\n", pref, "", "")
        msg = "FVS49 WARNING: VOLUME KEYWORD HAS BEEN RECOGNIZED BUT HAS BEEN DEACTIVATED BY A PREVIOUS CALL TO USE FIAVBC FOR COMPUTATION OF CUBIC FOOT VOLUMES"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(50)
        @printf(io, "\n%sFVS50 WARNING: DEFECT / MCDEFECT / MCFDLN KEYWORD HAS BEEN RECOGNIZED \n%12sBUT HAS BEEN DEACTIVATED BY A PREVIOUS CALL TO USE FIAVBC \n%12sFOR COMPUTATION OF CUBIC FOOT VOLUMES.\n%12sSETTING BOARD FOOT VALUES WITH DEFECT KEYWORD IS PERMITTED.\n", pref, "", "", "")
        msg = "FVS50 WARNING: DEFECT / MCDEFECT / MCFDLN KEYWORD HAS BEEN RECOGNIZED BUT HAS BEEN DEACTIVATED BY A PREVIOUS CALL TO USE FIAVBC FOR COMPUTATION OF CUBIC FOOT VOLUMES. SETTING BOARD FOOT VALUES WITH DEFECT KEYWORD IS PERMITTED."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(51)
        @printf(io, "\n%sFVS51 WARNING: BFFDLN KEYWORD HAS BEEN RECOGNIZED.\n%12sDUE A PREVIOUS CALL TO USE FIAVBC, BFFDLN WILL ONLY APPLY TO COMPUTATION OF BOARD FOOT VOLUMES\n%12sBUT WILL NOT AFFECT CUBIC SAWLOG VOLUMES\n", pref, "", "")
        msg = "FVS51 WARNING: BFFDLN KEYWORD HAS BEEN RECOGNIZED. DUE A PREVIOUS CALL TO USE FIAVBC, BFFDLN WILL ONLY APPLY TO COMPUTATION OF BOARD FOOT VOLUMES BUT WILL NOT AFFECT CUBIC SAWLOG VOLUMES"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(52)
        @printf(io, "\n%sFVS52 WARNING: USE OF DATABASE KEYWORDS VBCSUMDB, VBCTRLDB, VBCCUTDB, VBCATRDB\n%12sMUST INCLUDE USE OF BASE KEYWORD FIAVBC.\n", pref, "")
        msg = "FVS52 WARNING: USE OF DATABASE KEYWORDS VBCSUMDB, VBCTRLDB, VBCCUTDB, VBCATRDBMUST INCLUDE USE OF BASE KEYWORD FIAVBC."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(53)
        @printf(io, "\n%sFVS53 WARNING: INVALID ATTEMPT TO SET SCUFT IN MINHARV KEYWORD.  VALUE WILL BE IGNORED.\n", pref)
        msg = "FVS53 WARNING: INVALID ATTEMPT TO SET SCUFT IN MINHARV KEYWORD.  VALUE WILL BE IGNORED."
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    elseif ierrn == Int32(54)
        @printf(io, "\n%sFVS54 WARNING: INVALID SITE INDEX / SITE SPECIES CODE USED.  DEFAULT VALUE HAS BEEN USED\n", pref)
        msg = "FVS54 WARNING: INVALID SITE INDEX / SITE SPECIES CODE USED.  DEFAULT VALUE HAS BEEN USED"
        if ICCODE < Int32(2); global ICCODE = Int32(1); end

    else
        @printf(io, "\n%sFVS ERROR: UNKNOWN ERROR CODE %d\n", pref, ierrn)
        msg = @sprintf("FVS ERROR: UNKNOWN ERROR CODE %d", ierrn)
        if ICCODE < Int32(2); global ICCODE = Int32(2); end
    end

    DBSERROR(NPLT, msg)
    if lretrn
        return nothing
    end
    fvsSetRtnCode(ICCODE)
    return nothing
end

function GRSTOP()
    fvsSetRtnCode(ICCODE)
    return nothing
end

function fvsGetICCode(i::Ref{Int32})
    i[] = ICCODE
    return nothing
end
