# base/spctrn.jl — SPCTRN: species code translation/substitution table
# Translated from: bin/FVSsn_buildDir/spctrn.f (870 lines)
#
# Called from INTREE when the input species code is not recognized in the
# current variant's NSP table.  Searches ASPT (562 rows × 7 cols) for the
# input code in column 1 (FVS alpha), 2 (FIA numeric), or 3 (PLANTS symbol),
# then selects the variant-specific target code from columns 4-7 (CS/LS/NE/SN),
# and finally finds the target species index in the NSP array.
#
# Returns the matched species sequence number (1..MAXSP), or 0 if not found,
# or the variant's catch-all "other" species if SPCOUT remains unset.

# ASPT columns: (alpha, FIA, PLANTS, CS_target, LS_target, NE_target, SN_target)
# All strings use Fortran-width padding; comparison trims trailing spaces.
const _SPCTRN_MAXASPT = 562
const _SPCTRN_ASPT = (
    ("FR ","010","ABIES   ","OS ","BF ","BF ","FR "),
    ("BF ","012","ABBA    ","OS ","BF ","BF ","FR "),
    ("   ","016","ABFR    ","OS ","BF ","BF ","FR "),
    ("   ","300","ACACI   ","OH ","OH ","OH ","OH "),
    ("   ","303","ACFA    ","OH ","OH ","OH ","OH "),
    ("   ","304","ACGR    ","OH ","OH ","OH ","OH "),
    ("MP ","310","ACER    ","RM ","SM ","SM ","RM "),
    ("FM ","311","ACBA3   ","SM ","SM ","SM ","FM "),
    ("   ","   ","ACCA5   ","BE ","BE ","BE ","BE "),
    ("   ","   ","ACGI    ","RM ","RM ","RM ","RM "),
    ("   ","322","ACGR3   ","BE ","MM ","BE ","BE "),
    ("CM ","323","ACLE    ","SM ","SM ","SM ","SM "),
    ("BE ","313","ACNE2   ","BE ","BE ","BE ","BE "),
    ("   ","   ","ACNEN   ","BE ","BE ","BE ","BE "),
    ("   ","   ","ACNET   ","BE ","BE ","BE ","BE "),
    ("   ","   ","ACNEV   ","BE ","BE ","BE ","BE "),
    ("BM ","314","ACNI5   ","SM ","BM ","BM ","SM "),
    ("   ","   ","ACPA2   ","RM ","RM ","RM ","RM "),
    ("ST ","315","ACPE    ","BE ","ST ","ST ","BE "),
    ("   ","320","ACPL    ","SM ","SM ","SM ","SM "),
    ("   ","   ","ACPS    ","SM ","SM ","SM ","SM "),
    ("RM ","316","ACRU    ","RM ","RM ","RM ","RM "),
    ("   ","   ","ACRUD   ","RM ","RM ","RM ","RM "),
    ("   ","   ","ACRUR   ","RM ","RM ","RM ","RM "),
    ("   ","   ","ACRUT   ","RM ","RM ","RM ","RM "),
    ("SV ","317","ACSA2   ","SV ","SV ","SV ","SV "),
    ("SM ","318","ACSA3   ","SM ","SM ","SM ","SM "),
    ("   ","   ","ACSAS   ","SM ","SM ","SM ","SM "),
    ("   ","   ","ACSAS2  ","SM ","SM ","SM ","SM "),
    ("MM ","319","ACSP2   ","BE ","MM ","BE ","BE "),
    ("BU ","330","AESCU   ","OB ","OH ","BU ","BU "),
    ("YY ","332","AEFL    ","OB ","OH ","YY ","BU "),
    ("OB ","331","AEGL    ","OB ","OH ","BU ","BU "),
    ("   ","   ","AEGLG   ","OB ","OH ","BU ","BU "),
    ("   ","334","AEGLA   ","OB ","OH ","BU ","BU "),
    ("   ","   ","AEHI    ","OB ","OH ","BU ","BU "),
    ("   ","336","AEPA    ","OH ","OH ","OH ","OH "),
    ("   ","   ","AEPAP   ","OH ","OH ","OH ","OH "),
    ("   ","337","AESY    ","OH ","OH ","OH ","OH "),
    ("   ","   ","AILAN   ","OH ","OH ","AI ","OH "),
    ("AI ","341","AIAL    ","OH ","OH ","AI ","OH "),
    ("   ","345","ALJU    ","OH ","OH ","OH ","OH "),
    ("   ","350","ALNUS   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ALFA4   ","OH ","OH ","OH ","OH "),
    ("   ","355","ALGL2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ALIN2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ALINR   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ALSE2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ALVI5   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ALVIC   ","OH ","OH ","OH ","OH "),
    ("SE ","356","AMELA   ","OH ","OH ","SE ","OH "),
    ("   ","357","AMAR3   ","OH ","OH ","SE ","OH "),
    ("   ","   ","AMARA4  ","OH ","OH ","SE ","OH "),
    ("   ","   ","AMARA5  ","OH ","OH ","SE ","OH "),
    ("   ","   ","AMBA    ","OH ","OH ","SE ","OH "),
    ("   ","   ","AMIN2   ","OH ","OH ","SE ","OH "),
    ("   ","   ","AMLA    ","OH ","OH ","SE ","OH "),
    ("   ","358","AMSA    ","OH ","OH ","SE ","OH "),
    ("   ","   ","ARSP2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ASIMI   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ASOB6   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ASPA18  ","OH ","OH ","OH ","OH "),
    ("   ","367","ASTR    ","OH ","OH ","OH ","OH "),
    ("   ","986","AVGE    ","OH ","OH ","OH ","OH "),
    ("BB ","370","BETUL   ","RB ","PB ","YB ","BB "),
    ("YB ","371","BEAL2   ","RB ","YB ","YB ","BB "),
    ("SB ","372","BELE    ","RB ","YB ","SB ","SB "),
    ("RB ","373","BENI    ","RB ","PB ","RB ","BB "),
    ("WR ","374","BEOC2   ","RB ","PB ","WR ","BB "),
    ("PB ","375","BEPA    ","RB ","PB ","PB ","BB "),
    ("   ","   ","BEPAC2  ","RB ","PB ","PB ","BB "),
    ("   ","   ","BEPAP   ","RB ","PB ","PB ","BB "),
    ("   ","   ","BEPE3   ","RB ","PB ","PB ","BB "),
    ("GB ","379","BEPO    ","RB ","YB ","GB ","BB "),
    ("   ","   ","BEPU5   ","RB ","YB ","GB ","BB "),
    ("   ","   ","BEPUP4  ","RB ","YB ","GB ","BB "),
    ("   ","   ","BEPU4   ","RB ","PB ","YB ","BB "),
    ("   ","377","BEUB    ","RB ","PB ","RB ","BB "),
    ("   ","   ","BRPA4   ","OH ","OH ","OH ","OH "),
    ("   ","854","BUSI    ","OH ","OH ","OH ","OH "),
    ("   ","   ","CARPI   ","AH ","AH ","AH ","AH "),
    ("AH ","391","CACA18  ","AH ","AH ","AH ","AH "),
    ("   ","   ","CACAC2  ","AH ","AH ","AH ","AH "),
    ("   ","   ","CACAV   ","AH ","AH ","AH ","AH "),
    ("HI ","400","CARYA   ","HI ","BH ","HI ","HI "),
    ("MH ","409","CAAL27  ","MH ","PH ","MH ","HI "),
    ("WH ","401","CAAQ2   ","WH ","BH ","HI ","HI "),
    ("   ","   ","CABR16  ","HI ","BH ","HI ","HI "),
    ("   ","413","CACA38  ","SH ","SH ","HI ","HI "),
    ("BH ","402","CACO15  ","BH ","BH ","HI ","HI "),
    ("   ","411","CAFL6   ","BI ","PH ","HI ","HI "),
    ("PH ","403","CAGL8   ","PH ","PH ","PH ","HI "),
    ("PE ","404","CAIL2   ","PE ","BH ","HI ","HI "),
    ("SL ","405","CALA21  ","SL ","SH ","SL ","HI "),
    ("   ","   ","CALE13  ","HI ","BH ","HI ","HI "),
    ("   ","406","CAMY    ","PE ","BH ","HI ","HI "),
    ("   ","412","CAOV3   ","PH ","PH ","HI ","HI "),
    ("SH ","407","CAOV2   ","SH ","SH ","SH ","HI "),
    ("   ","410","CAPA24  ","PH ","PH ","HI ","HI "),
    ("   ","   ","CASC16  ","PH ","PH ","HI ","HI "),
    ("BI ","408","CATE9   ","BI ","PH ","HI ","HI "),
    ("   ","420","CASTA   ","OH ","AC ","OH ","OH "),
    ("AC ","421","CADE12  ","OH ","AC ","OH ","OH "),
    ("   ","424","CAMO83  ","OH ","AC ","OH ","OH "),
    ("   ","422","CAPU9   ","OH ","AC ","OH ","OH "),
    ("   ","423","CAPUO   ","OH ","AC ","OH ","OH "),
    ("   ","   ","CAPUP3  ","OH ","AC ","OH ","OH "),
    ("CA ","450","CATAL   ","CA ","OH ","OH ","CA "),
    ("   ","451","CABI8   ","CA ","OH ","OH ","CA "),
    ("   ","   ","CAOV5   ","CA ","OH ","OH ","CA "),
    ("   ","452","CASP8   ","CA ","OH ","OH ","CA "),
    ("   ","   ","CEDRU   ","JU ","RC ","WC ","JU "),
    ("HB ","460","CELTI   ","HK ","HK ","HK ","HB "),
    ("SG ","461","CELA    ","SG ","HK ","HK ","HB "),
    ("   ","   ","CELAL   ","SG ","HK ","HK ","HB "),
    ("   ","463","CELAR   ","SG ","HK ","HK ","HB "),
    ("   ","   ","CELAT8  ","SG ","HK ","HK ","HB "),
    ("HK ","462","CEOC    ","HK ","HK ","HK ","HB "),
    ("   ","   ","CETE    ","HK ","HK ","HK ","HB "),
    ("   ","   ","CERCI2  ","RD ","OH ","OH ","RD "),
    ("RD ","471","CECA4   ","RD ","OH ","OH ","RD "),
    ("   ","   ","CECAC   ","RD ","OH ","OH ","RD "),
    ("   ","   ","CECAT   ","RD ","OH ","OH ","RD "),
    ("   ","040","CHAMA4  ","OS ","OS ","AW ","JU "),
    ("AW ","043","CHTH2   ","OS ","OS ","AW ","JU "),
    ("   ","   ","CLADR   ","OH ","OH ","OH ","OH "),
    ("   ","481","CLKE    ","OH ","OH ","OH ","OH "),
    ("   ","987","COER2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","CORU17  ","OH ","OH ","OH ","OH "),
    ("   ","490","CORNU   ","DW ","DW ","DW ","DW "),
    ("   ","   ","COAL2   ","DW ","DW ","DW ","DW "),
    ("   ","   ","CODR    ","DW ","DW ","DW ","DW "),
    ("DW ","491","COFL2   ","DW ","DW ","DW ","DW "),
    ("   ","   ","COFO    ","DW ","DW ","DW ","DW "),
    ("   ","   ","CORU    ","DW ","DW ","DW ","DW "),
    ("   ","   ","COSE16  ","DW ","DW ","DW ","DW "),
    ("   ","   ","COSES   ","OH ","OH ","OH ","OH "),
    ("   ","   ","COCO10  ","OH ","OH ","OH ","OH "),
    ("   ","996","COOB2   ","OH ","OH ","OH ","OH "),
    ("HT ","500","CRATA   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRAM4   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRBE2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRBR    ","HT ","HT ","HT ","OH "),
    ("   ","503","CRBR3   ","HT ","HT ","HT ","OH "),
    ("   ","504","CRCA    ","HT ","HT ","HT ","OH "),
    ("   ","505","CRCH    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRCO2   ","HT ","HT ","HT ","OH "),
    ("   ","501","CRCR2   ","HT ","HT ","HT ","OH "),
    ("   ","506","CRDI    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRDI4   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRDI9   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRDI10  ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRDO3   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRDO2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CREN    ","HT ","HT ","HT ","OH "),
    ("   ","507","CRFL    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRFU2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRIM    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRIN10  ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRIN3   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRIR    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRIR2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRMA3   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRMA4   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRMA5   ","HT ","HT ","HT ","OH "),
    ("   ","502","CRMO2   ","HT ","HT ","HT ","OH "),
    ("   ","508","CRMO3   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRNI    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CROP    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CROV2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRPE13  ","HT ","HT ","HT ","OH "),
    ("   ","509","CRPE    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRPH    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRPR2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRPU    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRRE3   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRSP    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRSU5   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRTR2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRUN    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRVI2   ","HT ","HT ","HT ","OH "),
    ("   ","   ","CRWA    ","HT ","HT ","HT ","OH "),
    ("   ","   ","CULA    ","OS ","OS ","OS ","OS "),
    ("   ","050","CUPRE   ","JU ","RC ","WC ","JU "),
    ("   ","051","CUAR    ","JU ","RC ","WC ","JU "),
    ("   ","520","DIOSP   ","PS ","OH ","PS ","PS "),
    ("   ","522","DITE3   ","PS ","OH ","PS ","PS "),
    ("PS ","521","DIVI5   ","PS ","OH ","PS ","PS "),
    ("   ","   ","DIPA9   ","OH ","OH ","OH ","OH "),
    ("   ","   ","ELAEA   ","OH ","OH ","OH ","OH "),
    ("   ","997","ELAN    ","OH ","OH ","OH ","OH "),
    ("   ","   ","ERJA3   ","OH ","OH ","OH ","OH "),
    ("   ","510","EUCAL   ","OH ","OH ","OH ","OH "),
    ("   ","512","EUCA2   ","OH ","OH ","OH ","OH "),
    ("   ","513","EUGR12  ","OH ","OH ","OH ","OH "),
    ("   ","   ","FAGUS   ","AB ","AB ","AB ","AB "),
    ("AB ","531","FAGR    ","AB ","AB ","AB ","AB "),
    ("   ","   ","FASY    ","AB ","AB ","AB ","AB "),
    ("AS ","540","FRAXI   ","AS ","GA ","AS ","AS "),
    ("WA ","541","FRAM2   ","WA ","WA ","WA ","WA "),
    ("   ","548","FRCA3   ","AS ","GA ","AS ","AS "),
    ("BA ","543","FRNI    ","BA ","BA ","BA ","BA "),
    ("GA ","544","FRPE    ","GA ","GA ","GA ","GA "),
    ("PA ","545","FRPR    ","PA ","WA ","PA ","AS "),
    ("UA ","546","FRQU    ","UA ","WA ","AS ","AS "),
    ("   ","549","FRTE    ","AS ","GA ","AS ","AS "),
    ("   ","547","FRVE2   ","AS ","GA ","AS ","AS "),
    ("   ","561","GIBI2   ","OH ","OH ","OH ","OH "),
    ("   ","550","GLEDI   ","HL ","BK ","BK ","HL "),
    ("   ","551","GLAQ    ","HL ","BK ","BK ","HL "),
    ("   ","   ","GLTE    ","HL ","BK ","BK ","HL "),
    ("HL ","552","GLTR    ","HL ","BK ","BK ","HL "),
    ("LB ","555","GOLA    ","OH ","OH ","OH ","LB "),
    ("KC ","571","GYDI    ","KC ","OH ","OH ","OH "),
    ("HA ","580","HALES   ","OH ","OH ","OH ","HA "),
    ("   ","581","HACA3   ","OH ","OH ","OH ","HA "),
    ("   ","582","HADI3   ","OH ","OH ","OH ","HA "),
    ("   ","   ","HATE3   ","OH ","OH ","OH ","HA "),
    ("   ","   ","HATET   ","OH ","OH ","OH ","HA "),
    ("   ","   ","ILEX    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILAM    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILCA    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILCO2   ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILCO    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILCR2   ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILDE    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILGL    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILLO    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILMO    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILMU    ","OH ","OH ","HY ","HY "),
    ("HY ","591","ILOP    ","OH ","OH ","HY ","HY "),
    ("   ","   ","ILOPO   ","OH ","OH ","HY ","HY "),
    ("   ","600","JUGLA   ","WN ","WN ","WN ","WN "),
    ("BN ","601","JUCI    ","BN ","BN ","BN ","BN "),
    ("   ","606","JUMA    ","WN ","WN ","WN ","WN "),
    ("   ","605","JUMI    ","WN ","WN ","WN ","WN "),
    ("WN ","602","JUNI    ","WN ","WN ","WN ","WN "),
    ("JU ","057","JUNIP   ","JU ","RC ","JU ","JU "),
    ("   ","061","JUAS    ","JU ","RC ","JU ","JU "),
    ("   ","059","JUCO11  ","JU ","RC ","JU ","JU "),
    ("   ","   ","JUCO6   ","JU ","RC ","JU ","JU "),
    ("   ","   ","JUCOD   ","JU ","RC ","JU ","JU "),
    ("   ","063","JUDE2   ","JU ","RC ","JU ","JU "),
    ("   ","   ","JUMO    ","JU ","RC ","JU ","JU "),
    ("   ","058","JUPI    ","JU ","RC ","JU ","JU "),
    ("   ","066","JUSC2   ","JU ","RC ","JU ","JU "),
    ("RC ","068","JUVI    ","RC ","RC ","RC ","JU "),
    ("   ","   ","JUVIV   ","RC ","RC ","RC ","JU "),
    ("   ","067","JUVIS   ","RC ","RC ","RC ","JU "),
    ("   ","988","LARA2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","LAPO    ","OH ","OH ","OH ","OH "),
    ("   ","070","LARIX   ","OS ","TA ","TA ","HM "),
    ("   ","   ","LADE2   ","OS ","TA ","TA ","HM "),
    ("TA ","071","LALA    ","OS ","TA ","TA ","HM "),
    ("SU ","611","LIST2   ","SU ","OH ","SU ","SU "),
    ("YP ","621","LITU    ","YP ","OH ","YP ","YP "),
    ("OO ","641","MAPO    ","OO ","OH ","OO ","OH "),
    ("MG ","650","MAGNO   ","CT ","OH ","MG ","MG "),
    ("CT ","651","MAAC    ","CT ","OH ","CT ","CT "),
    ("   ","   ","MAAS    ","CT ","OH ","MG ","MG "),
    ("   ","655","MAFR    ","CT ","OH ","MG ","MG "),
    ("MS ","652","MAGR4   ","CT ","OH ","MG ","MS "),
    ("ML ","654","MAMA2   ","CT ","OH ","CT ","ML "),
    ("   ","657","MAPY    ","CT ","OH ","MG ","MG "),
    ("   ","   ","MASO9   ","CT ","OH ","MG ","MG "),
    ("   ","   ","MAST6   ","CT ","OH ","MG ","MG "),
    ("   ","658","MATR    ","CT ","OH ","MG ","MG "),
    ("MV ","653","MAVI2   ","MV ","OH ","MV ","MV "),
    ("AP ","660","MALUS   ","OH ","AP ","AP ","AP "),
    ("   ","662","MAAN3   ","OH ","AP ","AP ","AP "),
    ("   ","   ","MAANA   ","OH ","AP ","AP ","AP "),
    ("   ","   ","MAANP   ","OH ","AP ","AP ","AP "),
    ("   ","   ","MABA    ","OH ","AP ","AP ","AP "),
    ("   ","   ","MABAB   ","OH ","AP ","AP ","AP "),
    ("   ","664","MAIO    ","OH ","AP ","AP ","AP "),
    ("   ","   ","MAIOI   ","OH ","AP ","AP ","AP "),
    ("   ","   ","MAPR    ","OH ","AP ","AP ","AP "),
    ("   ","   ","MAPU    ","OH ","AP ","AP ","AP "),
    ("   ","   ","MASO3   ","OH ","AP ","AP ","AP "),
    ("   ","   ","MASY2   ","OH ","AP ","AP ","AP "),
    ("   ","992","MEQU    ","OH ","OH ","OH ","OH "),
    ("   ","993","MEAZ    ","OH ","OH ","OH ","OH "),
    ("   ","   ","MIFO    ","OH ","OH ","OH ","OH "),
    ("   ","   ","MIPY2   ","OH ","OH ","OH ","OH "),
    ("MB ","680","MORUS   ","MB ","OH ","OH ","MB "),
    ("WM ","681","MOAL    ","MB ","OH ","OH ","MB "),
    ("   ","683","MOMI    ","MB ","OH ","OH ","MB "),
    ("   ","684","MONI    ","MB ","OH ","OH ","MB "),
    ("RY ","682","MORU2   ","MB ","OH ","OH ","MB "),
    ("   ","   ","MORUR   ","MB ","OH ","OH ","MB "),
    ("TL ","690","NYSSA   ","TL ","BG ","BG ","BG "),
    ("WT ","691","NYAQ2   ","WT ","BG ","WT ","WT "),
    ("TS ","694","NYBI    ","TS ","BG ","BG ","TS "),
    ("OG ","692","NYOG    ","WT ","BG ","WT ","WT "),
    ("BG ","693","NYSY    ","BG ","BG ","BG ","BG "),
    ("   ","   ","NYUR2   ","TL ","BG ","BG ","BG "),
    ("   ","   ","OSTRY   ","HH ","HH ","HH ","HH "),
    ("HH ","701","OSVI    ","HH ","HH ","HH ","HH "),
    ("   ","   ","OSVIV   ","HH ","HH ","HH ","HH "),
    ("SD ","711","OXAR    ","SD ","OH ","SD ","SD "),
    ("PW ","712","PATO2   ","OH ","OH ","PW ","OH "),
    ("   ","720","PERSE   ","OH ","OH ","OH ","RA "),
    ("RA ","721","PEBO    ","OH ","OH ","OH ","RA "),
    ("   ","   ","PEHU2   ","OH ","OH ","OH ","RA "),
    ("   ","   ","PEPA37  ","OH ","OH ","OH ","RA "),
    ("PI ","090","PICEA   ","OS ","WS ","PI ","PI "),
    ("NS ","091","PIAB    ","OS ","NS ","OH ","PI "),
    ("WS ","094","PIGL    ","OS ","WS ","WS ","PI "),
    ("BS ","095","PIMA    ","OS ","BS ","BS ","PI "),
    ("RS ","097","PIRU    ","OS ","BS ","RS ","PI "),
    ("OP ","100","PINUS   ","OS ","WP ","OP ","LP "),
    ("   ","   ","PIAR5   ","OS ","OS ","OP ","OS "),
    ("JP ","105","PIBA2   ","VP ","JP ","JP ","PU "),
    ("PU ","107","PICL    ","VP ","JP ","OP ","PU "),
    ("SP ","110","PIEC2   ","SP ","RN ","SP ","SP "),
    ("SA ","111","PIEL    ","LP ","RN ","LP ","SA "),
    ("   ","144","PIELE2  ","LP ","RN ","OP ","SA "),
    ("SR ","115","PIGL2   ","SP ","JP ","SP ","SR "),
    ("   ","136","PINI    ","LP ","RN ","RN ","LP "),
    ("LL ","121","PIPA2   ","LP ","RN ","LP ","LL "),
    ("TM ","123","PIPU5   ","VP ","JP ","TM ","TM "),
    ("RN ","125","PIRE    ","LP ","RN ","RN ","LP "),
    ("PP ","126","PIRI    ","VP ","JP ","PP ","PP "),
    ("PD ","128","PISE    ","LP ","JP ","PD ","PD "),
    ("   ","114","PIST3   ","WP ","WP ","WP ","WP "),
    ("WP ","129","PIST    ","WP ","WP ","WP ","WP "),
    ("SC ","130","PISY    ","VP ","SC ","SC ","PU "),
    ("LP ","131","PITA    ","LP ","RN ","LP ","LP "),
    ("VP ","132","PIVI2   ","VP ","JP ","VP ","VP "),
    ("   ","722","PLAQ    ","OH ","OH ","OH ","OH "),
    ("   ","729","PLATA   ","SY ","SY ","SY ","SY "),
    ("SY ","731","PLOC    ","SY ","SY ","SY ","SY "),
    ("CW ","740","POPUL   ","EC ","EC ","EC ","CW "),
    ("   ","   ","POAC5   ","EC ","EC ","EC ","CW "),
    ("   ","752","POAL7   ","BP ","BP ","BP ","BT "),
    ("   ","749","POAN3   ","EC ","EC ","EC ","CW "),
    ("BP ","741","POBA2   ","BP ","BP ","BP ","BT "),
    ("   ","   ","POBAB2  ","BP ","BP ","BP ","BT "),
    ("   ","   ","POCA19  ","EC ","EC ","EC ","CW "),
    ("   ","   ","POCA14  ","EC ","EC ","EC ","CW "),
    ("EC ","742","PODE3   ","EC ","EC ","EC ","CW "),
    ("   ","   ","PODED   ","EC ","EC ","EC ","CW "),
    ("   ","745","PODEM   ","EC ","EC ","EC ","CW "),
    ("   ","   ","PODEW   ","EC ","EC ","EC ","CW "),
    ("   ","748","POFR2   ","EC ","EC ","EC ","CW "),
    ("BT ","743","POGR4   ","BT ","BT ","BT ","BT "),
    ("PY ","744","POHE4   ","EC ","EC ","PY ","CW "),
    ("   ","753","PONI    ","BP ","BP ","BP ","BT "),
    ("   ","   ","POSM2   ","EC ","EC ","EC ","CW "),
    ("   ","   ","POTR10  ","QA ","QA ","QA ","BT "),
    ("QA ","746","POTR5   ","QA ","QA ","QA ","BT "),
    ("   ","755","PROSO   ","OH ","OH ","OH ","OH "),
    ("   ","756","PRGL2   ","OH ","OH ","OH ","OH "),
    ("   ","   ","PRGLG   ","OH ","OH ","OH ","OH "),
    ("   ","758","PRPU    ","OH ","OH ","OH ","OH "),
    ("PL ","760","PRUNU   ","OH ","PL ","PL ","AP "),
    ("   ","769","PRAL5   ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRALD   ","OH ","PL ","PL ","AP "),
    ("   ","766","PRAM    ","OH ","PL ","PL ","AP "),
    ("   ","770","PRAN3   ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRAR3   ","OH ","PL ","PL ","AP "),
    ("   ","771","PRAV    ","OH ","CC ","PR ","AP "),
    ("   ","   ","PRCA    ","OH ","CC ","PR ","AP "),
    ("   ","   ","PRCE2   ","OH ","CC ","PR ","AP "),
    ("   ","772","PRCE    ","OH ","CC ","PR ","AP "),
    ("   ","773","PRDO    ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRDOD   ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRHO    ","OH ","PL ","PL ","AP "),
    ("   ","774","PRMA    ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRME    ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRMU    ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRMY    ","OH ","PL ","PL ","AP "),
    ("   ","765","PRNI    ","OH ","PL ","PL ","AP "),
    ("PR ","761","PRPE2   ","OH ","PR ","PR ","AP "),
    ("   ","   ","PRPEP   ","OH ","PR ","PR ","AP "),
    ("   ","764","PRPE3   ","OH ","PL ","PL ","AP "),
    ("BC ","762","PRSE2   ","BC ","BC ","BC ","BC "),
    ("   ","   ","PRSEE   ","BC ","BC ","BC ","BC "),
    ("   ","   ","PRSU4   ","OH ","PR ","PR ","AP "),
    ("   ","   ","PRTO80  ","OH ","PR ","PR ","AP "),
    ("   ","   ","PRTR3   ","OH ","PL ","PL ","AP "),
    ("   ","   ","PRUM    ","OH ","PL ","PL ","AP "),
    ("CC ","763","PRVI    ","OH ","CC ","PR ","AP "),
    ("   ","   ","PRVID   ","OH ","CC ","PR ","AP "),
    ("   ","   ","PRVIV   ","OH ","CC ","PR ","AP "),
    ("   ","   ","PYRUS   ","OH ","PL ","PL ","AP "),
    ("   ","   ","PYCA80  ","OH ","PL ","PL ","AP "),
    ("   ","   ","PYCO    ","OH ","PL ","PL ","AP "),
    ("   ","   ","PYPY2   ","OH ","PL ","PL ","AP "),
    ("OK ","800","QUERC   ","WO ","WO ","OK ","WO "),
    ("   ","   ","QUAC2   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUAC80  ","BJ ","OH ","OK ","BJ "),
    ("WO ","802","QUAL    ","WO ","WO ","WO ","WO "),
    ("   ","803","QUAR    ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUAR2   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUAS3   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUAU    ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUBE    ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUBE3   ","BJ ","OH ","OK ","BJ "),
    ("SW ","804","QUBI    ","SW ","SW ","SW ","WO "),
    ("   ","   ","QUBO2   ","PO ","BR ","PO ","PO "),
    ("   ","   ","QUBU2   ","SO ","BO ","SO ","SO "),
    ("   ","   ","QUBU    ","PO ","BR ","PO ","PO "),
    ("   ","   ","QUCA    ","SO ","BO ","SO ","SO "),
    ("   ","   ","QUCA2   ","SO ","BO ","SO ","SO "),
    ("   ","   ","QUCH    ","PO ","BR ","PO ","PO "),
    ("SO ","806","QUCO2   ","SO ","BO ","SO ","SO "),
    ("   ","   ","QUCO5   ","BO ","BO ","BO ","BO "),
    ("   ","   ","QUCO3   ","BJ ","OH ","OK ","LO "),
    ("   ","   ","QUCR    ","BJ ","OH ","OK ","TO "),
    ("   ","   ","QUDE2   ","WK ","BO ","WK ","WK "),
    ("NP ","809","QUEL    ","PN ","NP ","PN ","SK "),
    ("   ","810","QUEM    ","BJ ","OH ","OK ","BJ "),
    ("SK ","812","QUFA    ","SK ","BO ","SK ","SK "),
    ("   ","   ","QUFU    ","BJ ","OH ","OK ","LO "),
    ("   ","814","QUGA    ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUGA3   ","SK ","BO ","SK ","SK "),
    ("   ","   ","QUGE2   ","BJ ","OH ","OK ","LO "),
    ("   ","   ","QUGR3   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUHE2   ","BJ ","OH ","OK ","LO "),
    ("   ","   ","QUHEH   ","BJ ","OH ","OK ","LO "),
    ("   ","   ","QUHY    ","BJ ","OH ","OK ","BJ "),
    ("   ","816","QUIL    ","BJ ","OH ","OK ","BJ "),
    ("QI ","817","QUIM    ","QI ","BO ","QI ","WK "),
    ("QN ","842","QUIN    ","BJ ","OH ","OK ","TO "),
    ("   ","   ","QUJO4   ","SK ","BO ","SK ","SK "),
    ("TO ","819","QULA2   ","BJ ","OH ","OK ","TO "),
    ("LK ","820","QULA3   ","WK ","BO ","WK ","LK "),
    ("OV ","822","QULY    ","OV ","BR ","OK ","OV "),
    ("   ","   ","QUMA    ","PO ","BR ","PO ","PO "),
    ("BR ","823","QUMA2   ","BR ","BR ","BR ","OV "),
    ("   ","   ","QUMAM   ","BR ","BR ","BR ","OV "),
    ("DP ","840","QUMA6   ","PO ","BR ","PO ","TO "),
    ("BJ ","824","QUMA3   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUMAM2  ","BJ ","OH ","OK ","BJ "),
    ("SN ","825","QUMI    ","SN ","WO ","SN ","SN "),
    ("   ","841","QUMI2   ","BJ ","OH ","OK ","TO "),
    ("   ","   ","QUMO    ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUMO3   ","BJ ","OH ","OK ","BJ "),
    ("CK ","826","QUMU    ","CK ","CK ","CK ","CK "),
    ("   ","   ","QUMY    ","BJ ","OH ","OK ","BJ "),
    ("WK ","827","QUNI    ","WK ","BO ","WK ","WK "),
    ("   ","829","QUOB    ","BJ ","OH ","OK ","BJ "),
    ("   ","844","QUOG    ","BJ ","OH ","OK ","LK "),
    ("CB ","813","QUPA5   ","CB ","BO ","CB ","CB "),
    ("PN ","830","QUPA2   ","PN ","NP ","PN ","SK "),
    ("   ","   ","QUPA4   ","BJ ","OH ","OK ","BJ "),
    ("WL ","831","QUPH    ","WL ","BO ","WL ","WK "),
    ("   ","845","QUPR    ","BJ ","OH ","OK ","TO "),
    ("CO ","832","QUPR2   ","CO ","WO ","CO ","CO "),
    ("   ","   ","QUPS    ","BJ ","OH ","OK ","TO "),
    ("   ","   ","QUPU80  ","BJ ","OH ","OK ","TO "),
    ("   ","   ","QURO2   ","WO ","WO ","WO ","WO "),
    ("RO ","833","QURU    ","RO ","RO ","RO ","RO "),
    ("   ","   ","QURUR   ","RO ","RO ","RO ","RO "),
    ("   ","   ","QURU4   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUSA    ","WO ","WO ","WO ","WO "),
    ("QS ","834","QUSH    ","QS ","BO ","SK ","QS "),
    ("   ","   ","QUSHS   ","QS ","BO ","SK ","QS "),
    ("   ","   ","QUSHS2  ","QS ","BO ","SK ","QS "),
    ("DO ","836","QUSI2   ","DO ","BR ","PO ","PO "),
    ("   ","   ","QUSI    ","PO ","BR ","PO ","PO "),
    ("   ","   ","QUSIB   ","PO ","BR ","PO ","PO "),
    ("   ","808","QUSIS   ","PO ","BR ","PO ","PO "),
    ("PO ","835","QUST    ","PO ","BR ","PO ","PO "),
    ("   ","   ","QUSU5   ","SK ","BO ","SK ","SK "),
    ("   ","   ","QUSU6   ","SK ","BO ","SK ","SK "),
    ("   ","   ","QUSU2   ","SK ","BO ","SK ","SK "),
    ("   ","   ","QUTA    ","BJ ","OH ","OK ","BJ "),
    ("NK ","828","QUTE    ","NK ","BO ","OK ","SK "),
    ("   ","   ","QUTO2   ","BJ ","OH ","OK ","BJ "),
    ("   ","   ","QUTU2   ","BJ ","OH ","OK ","BJ "),
    ("BO ","837","QUVE    ","BO ","BO ","BO ","BO "),
    ("LO ","838","QUVI    ","BJ ","OH ","OK ","LO "),
    ("   ","   ","ROBIN   ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROAM2   ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROHI    ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROHIF8  ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROHIH   ","BK ","BK ","BK ","BK "),
    ("   ","   ","RONE    ","BK ","BK ","BK ","BK "),
    ("BK ","901","ROPS    ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROVI    ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROVIH2  ","BK ","BK ","BK ","BK "),
    ("   ","   ","ROVIV   ","BK ","BK ","BK ","BK "),
    ("WI ","920","SALIX   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAAL    ","WI ","WI ","BL ","WI "),
    ("   ","927","SAAL2   ","WI ","WI ","BL ","WI "),
    ("   ","921","SAAM2   ","WI ","WI ","BL ","WI "),
    ("   ","925","SACA5   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SACI    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAEH    ","WI ","WI ","BL ","WI "),
    ("DM ","923","SAER    ","WI ","DM ","BL ","WI "),
    ("   ","   ","SAEX    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAFL    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAFR    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAGL3   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAGO    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SALA6   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAMY2   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAMYA   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAMYM   ","WI ","WI ","BL ","WI "),
    ("BL ","922","SANI    ","BL ","BL ","BL ","WI "),
    ("   ","   ","SAPE3   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAPE12  ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAPE4   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAPE5   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAPU2   ","WI ","WI ","BL ","WI "),
    ("   ","926","SAPY    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SARU3   ","WI ","WI ","BL ","WI "),
    ("   ","929","SASE10  ","WI ","WI ","BL ","WI "),
    ("   ","   ","SASE    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SATA    ","WI ","WI ","BL ","WI "),
    ("   ","   ","SAVI2   ","WI ","WI ","BL ","WI "),
    ("   ","   ","SASAD   ","WI ","WI ","BL ","WI "),
    ("SS ","931","SAAL5   ","SS ","SS ","SS ","SS "),
    ("   ","934","SORBU   ","OH ","MA ","OH ","OH "),
    ("MA ","935","SOAM3   ","OH ","MA ","OH ","OH "),
    ("   ","936","SOAU    ","OH ","MA ","OH ","OH "),
    ("   ","220","TAXOD   ","BY ","OS ","WC ","BY "),
    ("PC ","222","TAAS    ","BY ","OS ","WC ","PC "),
    ("BY ","221","TADI2   ","BY ","OS ","WC ","BY "),
    ("   ","230","TAXUS   ","OS ","OS ","OS ","OS "),
    ("   ","232","TAFL    ","OS ","OS ","OS ","OS "),
    ("OC ","240","THUJA   ","OS ","WC ","WC ","JU "),
    ("WC ","241","THOC2   ","OS ","WC ","WC ","JU "),
    ("BD ","950","TILIA   ","BW ","BW ","BW ","BD "),
    ("BW ","951","TIAM    ","BW ","BW ","BW ","BD "),
    ("   ","   ","TIAMA   ","BW ","BW ","BW ","BD "),
    ("   ","953","TIAMC   ","BW ","BW ","BW ","BD "),
    ("WB ","952","TIAMH   ","BW ","BW ","BW ","BD "),
    ("   ","   ","TICO2   ","BW ","BW ","BW ","BD "),
    ("   ","   ","TIEU4   ","BW ","BW ","BW ","BD "),
    ("   ","   ","TIHE    ","BW ","BW ","BW ","BD "),
    ("HM ","260","TSUGA   ","OS ","EH ","HM ","HM "),
    ("EH ","261","TSCA    ","OS ","EH ","EH ","HM "),
    ("   ","262","TSCA2   ","OS ","EH ","HM ","HM "),
    ("EL ","970","ULMUS   ","EL ","AE ","EL ","EL "),
    ("WE ","971","ULAL    ","WE ","AE ","EL ","WE "),
    ("AE ","972","ULAM    ","AE ","AE ","AE ","AE "),
    ("   ","973","ULCR    ","EL ","RL ","EL ","EL "),
    ("   ","   ","ULPA    ","EL ","RL ","EL ","EL "),
    ("   ","   ","ULPR    ","EL ","RL ","EL ","EL "),
    ("SI ","974","ULPU    ","SI ","AE ","EL ","EL "),
    ("RL ","975","ULRU    ","RL ","RL ","RL ","RL "),
    ("   ","976","ULSE    ","EL ","RL ","EL ","EL "),
    ("RE ","977","ULTH    ","RE ","RE ","EL ","EL "),
    ("   ","299","        ","OS ","OS ","OS ","OS "),
    ("   ","998","        ","OH ","OH ","OH ","OH "),
    ("   ","999","        ","OH ","OH ","OH ","OT "),
    ("CH ","   ","        ","OH ","OH ","OH ","OH "),
    ("HS ","   ","        ","HI ","BH ","HI ","HI "),
    ("NC ","   ","        ","OH ","OH ","OH ","OH "),
    ("OH ","   ","        ","OH ","OH ","OH ","OH "),
    ("OL ","   ","        ","OH ","OH ","OH ","OH "),
    ("OS ","   ","        ","OS ","OS ","OS ","OS "),
    ("OT ","   ","        ","OH ","OH ","OH ","OT "),
    ("UH ","   ","        ","OH ","OH ","OH ","OH "),
    ("   ","   ","2TB     ","OH ","OH ","OH ","OH "),
    ("   ","   ","2TD     ","OH ","OH ","OH ","OH "),
    ("   ","   ","2TE     ","OS ","OS ","OS ","OS "),
    ("   ","   ","2TN     ","OS ","OS ","OS ","OS "),
    ("   ","   ","2TREE   ","OH ","OH ","OH ","OT "),
)

function SPCTRN(spcin::AbstractString, ::Integer)::Int32
    var   = strip(VARACD)
    ispc1 = Int32(0)
    spcout = "XX "

    spcin_tr = rstrip(spcin)

    ijspin = Int32(3)
    for i in 1:_SPCTRN_MAXASPT
        row  = _SPCTRN_ASPT[i]
        alfa  = rstrip(row[1])
        fia   = rstrip(row[2])
        plnt  = rstrip(row[3])
        if !isempty(alfa) && spcin_tr == alfa
            ijspin = Int32(1)
            spcout = _spctrn_variant_col(row, var)
            break
        elseif !isempty(fia) && spcin_tr == fia
            ijspin = Int32(2)
            spcout = _spctrn_variant_col(row, var)
            break
        elseif !isempty(plnt) && spcin_tr == plnt
            ijspin = Int32(3)
            spcout = _spctrn_variant_col(row, var)
            break
        end
    end

    # If no match found, assign catch-all "other" species for this variant
    if rstrip(spcout) == "XX"
        if var == "CS"; ispc1 = Int32(85)
        elseif var == "LS"; ispc1 = Int32(49)
        elseif var == "NE"; ispc1 = Int32(98)
        elseif var == "SN"; ispc1 = Int32(90)
        end
        if JSPINDEF <= Int32(0); global JSPINDEF = ijspin; end
        if ispc1 > 0; global JSPIN[Int(ispc1)] = ijspin; end
        return ispc1
    end

    # Find spcout in the variant's NSP table
    # Fortran: IF (SPCOUT(1:2).EQ.NSP(J2,1)(1:2)) — compare only first 2 chars
    spcout2 = rstrip(spcout)
    for j2 in 1:MAXSP
        nsp1 = NSP[j2, 1]
        if length(nsp1) >= 2 && spcout2 == nsp1[1:2]
            ispc1 = Int32(j2)
            break
        end
    end
    # Fortran latent bug: if ispc1 still 0, JSPIN(0) overwrites adjacent memory.
    # In Julia this crashes. Default to variant "other" species to match expected behavior.
    if ispc1 == Int32(0)
        if var == "CS"; ispc1 = Int32(85)
        elseif var == "LS"; ispc1 = Int32(49)
        elseif var == "NE"; ispc1 = Int32(98)
        else;               ispc1 = Int32(90)   # SN default "OT"
        end
    end

    if JSPINDEF <= Int32(0); global JSPINDEF = ijspin; end
    if ispc1 > 0; global JSPIN[Int(ispc1)] = ijspin; end
    return ispc1
end

@inline function _spctrn_variant_col(row::Tuple, var::AbstractString)::String
    if var == "CS"; return row[4]
    elseif var == "LS"; return row[5]
    elseif var == "NE"; return row[6]
    else;              return row[7]   # SN (default)
    end
end
